services:
  n8n:
    image: n8nio/n8n:latest
    user: "1000:1000"
    container_name: n8n-dev
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./secrets/.env
    environment:
      - TZ=America/Toronto
      - N8N_DEFAULT_EXECUTION_TIMEOUT=3600
      - N8N_PUSH_BACKEND_TIMEOUT=3600
    volumes:
      - /home/ubuntu/n8n-projects/n8n_data/.n8n:/home/node/.n8n
      - /home/ubuntu/n8n-projects:/home/node/n8n-projects
